version: "3"
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=knocker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:
